import React, { useState } from 'react';
import { Trophy, Lightbulb, CheckCircle2, XCircle, ArrowRight } from 'lucide-react';
import { MathView } from '../common/MathView';
import confetti from 'canvas-confetti';

interface DivCurlChallenge {
  question: string;
  mathPrompt?: string;
  correctAnswer: number;
  hint: string;
  explanation: string;
}

const DC_CHALLENGES: DivCurlChallenge[] = [
  {
    question: 'For the 2D field F(x,y) = 3x i + 5y j, what is the divergence ∇·F everywhere in the plane?',
    mathPrompt: '\\nabla \\cdot \\vec{F} = \\frac{\\partial(3x)}{\\partial x} + \\frac{\\partial(5y)}{\\partial y} = ?',
    correctAnswer: 8,
    hint: '3 + 5 = 8.',
    explanation: '∂(3x)/∂x + ∂(5y)/∂y = 3 + 5 = 8.',
  },
  {
    question: 'For the velocity field F(x,y) = -3y i + 3x j, what is the z-component of curl (∇×F)z?',
    mathPrompt: '(\\nabla \\times \\vec{F})_z = \\frac{\\partial(3x)}{\\partial x} - \\frac{\\partial(-3y)}{\\partial y} = ?',
    correctAnswer: 6,
    hint: '3 - (-3) = 3 + 3 = 6.',
    explanation: '3 - (-3) = 6 (counterclockwise rotation).',
  },
  {
    question: 'For an electrostatic field generated by a point charge in empty space (away from the charge), what is the divergence ∇·E?',
    mathPrompt: '\\nabla \\cdot \\vec{E} = \\frac{\\rho}{\\varepsilon_0} = ?',
    correctAnswer: 0,
    hint: 'Gauss Law with zero charge density ρ = 0 gives div = 0.',
    explanation: 'In charge-free space, Gauss Law states ∇·E = 0.',
  },
];

export const DivCurlChallengeSection: React.FC = () => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [userAnswer, setUserAnswer] = useState('');
  const [feedback, setFeedback] = useState<'idle' | 'correct' | 'incorrect'>('idle');
  const [streak, setStreak] = useState(0);

  const current = DC_CHALLENGES[currentIndex];

  const handleCheck = () => {
    const val = parseInt(userAnswer.trim(), 10);
    if (isNaN(val)) return;

    if (val === current.correctAnswer) {
      setFeedback('correct');
      setStreak(prev => prev + 1);
      try {
        confetti({ particleCount: 50, spread: 60, origin: { y: 0.85 } });
      } catch {
        // Ignore
      }
    } else {
      setFeedback('incorrect');
      setStreak(0);
    }
  };

  const handleNext = () => {
    setCurrentIndex((prev) => (prev + 1) % DC_CHALLENGES.length);
    setUserAnswer('');
    setFeedback('idle');
  };

  return (
    <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
      {/* Challenge Card */}
      <div className="md:col-span-8 bg-white rounded-3xl p-5 md:p-6 border border-pink-100/80 shadow-sm flex flex-col justify-between space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-xl bg-pink-50 flex items-center justify-center text-pink-600">
              <Trophy className="w-4 h-4" />
            </div>
            <h3 className="text-sm font-extrabold text-slate-900 tracking-tight font-sans">
              Challenge
            </h3>
          </div>
          {streak > 0 && (
            <span className="px-2.5 py-0.5 bg-amber-50 text-amber-700 border border-amber-200 rounded-full text-[11px] font-bold">
              🔥 Streak: {streak}
            </span>
          )}
        </div>

        <div className="text-xs text-slate-700 font-medium space-y-1">
          <p>{current.question}</p>
          {current.mathPrompt && (
            <div className="py-1">
              <MathView math={current.mathPrompt} />
            </div>
          )}
        </div>

        {/* Input Row */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2 pt-1">
          <span className="text-xs font-semibold text-slate-500 whitespace-nowrap">
            Your answer
          </span>
          <input
            type="number"
            placeholder="Enter number"
            value={userAnswer}
            onChange={(e) => {
              setUserAnswer(e.target.value);
              if (feedback !== 'idle') setFeedback('idle');
            }}
            onKeyDown={(e) => {
              if (e.key === 'Enter') handleCheck();
            }}
            className="flex-1 px-3.5 py-2 text-xs rounded-xl border border-slate-200 bg-slate-50 focus:bg-white focus:outline-none focus:ring-2 focus:ring-pink-500/20 focus:border-pink-500 font-mono"
          />
          <button
            onClick={handleCheck}
            className="px-5 py-2 bg-pink-600 hover:bg-pink-700 text-white text-xs font-bold rounded-xl shadow-md shadow-pink-500/20 transition-transform active:scale-95"
          >
            Check
          </button>
        </div>

        {feedback === 'correct' && (
          <div className="flex items-center justify-between bg-pink-50 text-pink-950 p-2.5 rounded-xl border border-pink-200 text-xs animate-in fade-in">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-pink-600 shrink-0" />
              <span><strong>Correct!</strong> {current.explanation}</span>
            </div>
            <button
              onClick={handleNext}
              className="px-3 py-1 bg-pink-600 hover:bg-pink-700 text-white text-[11px] font-bold rounded-lg transition-colors flex items-center gap-1 shrink-0 ml-2"
            >
              Next <ArrowRight className="w-3 h-3" />
            </button>
          </div>
        )}

        {feedback === 'incorrect' && (
          <div className="flex items-center justify-between bg-rose-50 text-rose-800 p-2.5 rounded-xl border border-rose-200 text-xs animate-in fade-in">
            <div className="flex items-center gap-2">
              <XCircle className="w-4 h-4 text-rose-600 shrink-0" />
              <span><strong>Not quite.</strong> {current.hint}</span>
            </div>
            <button
              onClick={() => setFeedback('idle')}
              className="text-[11px] font-bold text-rose-700 underline ml-2"
            >
              Try Again
            </button>
          </div>
        )}
      </div>

      {/* Tip Card */}
      <div className="md:col-span-4 bg-white rounded-3xl p-5 md:p-6 border border-pink-100/80 shadow-sm flex flex-col justify-between space-y-3">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-xl bg-amber-50 flex items-center justify-center text-amber-600">
            <Lightbulb className="w-4 h-4" />
          </div>
          <h3 className="text-sm font-extrabold text-slate-900 tracking-tight font-sans">
            Tip
          </h3>
        </div>

        <p className="text-xs text-slate-600 font-medium leading-relaxed">
          <strong className="text-pink-950">Maxwell's Equations:</strong> Electromagnetism is formulated entirely in terms of divergence and curl: <MathView math="\nabla \cdot \vec{E} = \rho/\varepsilon_0" />, <MathView math="\nabla \cdot \vec{B} = 0" />, and Faraday's <MathView math="\nabla \times \vec{E} = -\partial\vec{B}/\partial t" />.
        </p>

        <div className="text-[11px] text-pink-800 font-semibold bg-pink-50/60 p-2.5 rounded-xl border border-pink-100/60 font-mono">
          div = Flux Outflow | curl = Local Rotation
        </div>
      </div>
    </div>
  );
};
